# Generated by Django 4.0 on 2021-12-12 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('loc_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('loc_ltd', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('education', models.CharField(choices=[('HIGH', 'High School Diploma'), ('ASSO', 'Associate Degree'), ('UNDE', 'Undergraduate Degree'), ('POST', 'Postgraduate Degree')], max_length=4)),
                ('description', models.TextField(blank=True)),
                ('credit', models.IntegerField(default=0)),
            ],
        ),
    ]
