# Generated by Django 4.0 on 2021-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('High School Diplome', 'High School Diploma'), ('Associate Defree', 'Associate Degree'), ('Undergraduate Degree', 'Undergraduate Degree'), ('Postgradute Degree', 'Postgraduate Degree')], max_length=50),
        ),
    ]
