# Generated by Django 4.0 on 2021-12-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('High School Diploma', 'High School Diploma'), ('Associate Degree', 'Associate Degree'), ('Undergraduate Degree', 'Undergraduate Degree'), ('Postgradute Degree', 'Postgraduate Degree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
