# Generated by Django 4.0 on 2021-12-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorytags', '0001_initial'),
        ('offers', '0005_offer_tags'),
        ('profiles', '0003_alter_profile_education_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='profiles', to='categorytags.Interest'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offers',
            field=models.ManyToManyField(related_name='profiles', to='offers.Offer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='profiles', to='categorytags.Skill'),
        ),
        migrations.CreateModel(
            name='ProfileReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_giver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_receiver', to='profiles.profile')),
                ('review_receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_giver', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profiles.profile')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='profiles.profile')),
            ],
        ),
    ]
