# Generated by Django 4.0 on 2021-12-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFollowing',
            new_name='ProfileFollowRequest',
        ),
    ]
