# Generated by Django 4.0 on 2021-12-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_credit_offer_participants'),
        ('profiles', '0011_alter_profile_interests_alter_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinOfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_offer', to='offers.offer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joiner', to='profiles.profile')),
            ],
        ),
    ]
