# Generated by Django 4.0 on 2021-12-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_joinofferrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='outstanding_offers',
        ),
    ]
