# Generated by Django 4.0 on 2021-12-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_credit_offer_participants'),
        ('profiles', '0013_remove_profile_outstanding_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinOfferRequest',
            new_name='ProfileJoinOfferRequest',
        ),
    ]
