# Generated by Django 4.0 on 2021-12-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_rename_joinofferrequest_profilejoinofferrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
    ]
