# Generated by Django 4.0 on 2021-12-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_alter_offer_offer_status'),
        ('profiles', '0017_alter_profile_loc_long_alter_profile_loc_ltd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilereview',
            old_name='review_giver_id',
            new_name='review_giver',
        ),
        migrations.RenameField(
            model_name='profilereview',
            old_name='review_receiver_id',
            new_name='review_receiver',
        ),
        migrations.AddField(
            model_name='profilereview',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='offers.offer'),
        ),
    ]
