# Generated by Django 4.0 on 2021-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_rename_review_giver_id_profilereview_review_giver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilereview',
            name='review_receiver',
        ),
        migrations.AddField(
            model_name='profilereview',
            name='done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilereview',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilereview',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
