# Generated by Django 4.0 on 2021-12-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_city_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
