# Generated by Django 4.0 on 2021-12-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loc_long',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loc_ltd',
        ),
    ]
