# Generated by Django 4.0 on 2021-12-28 20:02

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_remove_profile_city_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(map_id='map', null=True),
        ),
    ]
