# Generated by Django 4.0 on 2021-12-28 20:10

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}, null=True),
        ),
    ]
