# Generated by Django 4.0 on 2021-12-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_remove_offer_approved_offer_approval_status'),
        ('profiles', '0028_remove_profile_address_remove_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilereview',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OwnerToParticipantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_owner', to='offers.offer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_participant', to='profiles.profile')),
            ],
        ),
    ]
