# Generated by Django 4.0 on 2021-12-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_alter_profilereview_rating_ownertoparticipantreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilereview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
