# Generated by Django 4.0 on 2021-12-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_alter_profilereview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilejoinofferrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
