# Generated by Django 4.0 on 2021-12-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_profilejoinofferrequest_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilejoinofferrequest',
            name='is_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
