# Generated by Django 4.0 on 2021-12-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
