# Generated by Django 4.0 on 2021-12-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_rename_owner_id_offer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
