# Generated by Django 4.0 on 2021-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_format',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=7),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Service', 'Service')], max_length=7),
        ),
    ]
