# Generated by Django 4.0 on 2021-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorytags', '0001_initial'),
        ('offers', '0004_alter_offer_offer_format_alter_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(related_name='offers', to='categorytags.OfferTag'),
        ),
    ]
