# Generated by Django 4.0 on 2021-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorytags', '0001_initial'),
        ('offers', '0005_offer_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='offers', to='categorytags.OfferTag'),
        ),
    ]
