# Generated by Django 4.0 on 2021-12-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_credit_offer_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
