# Generated by Django 4.0 on 2021-12-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_offer_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(choices=[('Event', 'Event'), ('Service', 'Service')], default='Active', max_length=10),
        ),
    ]
