# Generated by Django 4.0 on 2021-12-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_alter_offer_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
