# Generated by Django 4.0 on 2021-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_offer_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='approved',
        ),
        migrations.AddField(
            model_name='offer',
            name='approval_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Outstanding', 'Outstanding')], default='Outstanding', max_length=11),
        ),
    ]
