# Generated by Django 4.0 on 2022-01-01 10:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_remove_offer_approved_offer_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
