# Generated by Django 4.0 on 2022-01-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_offer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_status',
        ),
    ]
