# Generated by Django 4.0 on 2022-01-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_offer_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='loc_long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='loc_ltd',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
