# Generated by Django 4.0 on 2022-01-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_alter_offer_loc_long_alter_offer_loc_ltd'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_credit_earned',
            field=models.BooleanField(default=False),
        ),
    ]
